---
- name: Delete old Docker Swarm
  shell: docker swarm leave --force
  tags: swarm

- name: Initialize Docker Swarm
  shell: docker swarm init --advertise-addr 192.168.50.10
  tags: swarm

- name: Get the worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token
  tags: swarm

- debug: msg={{worker_token}}
